taller_reparacio_frontend_homepage:
    path:     /
    defaults: { _controller: TallerReparacioFrontendBundle:Default:index }

taller_reparacio_frontend_historic:
    path:     /historic
    defaults: { _controller: TallerReparacioFrontendBundle:Default:historic }

taller_reparacio_frontend_login:
    path:     /client/eliminar/{nif}
    defaults: { _controller: TallerReparacioFrontendBundle:Default:AAAAAAAAAAAAAPASSARALBACKENDDENBERNABEeliminar }