taller_reparacio_frontend_homepage:
    path:     /
    defaults: { _controller: TallerReparacioFrontendBundle:Default:index }

taller_reparacio_frontend_historic:
    path:     /historic
    defaults: { _controller: TallerReparacioFrontendBundle:Default:historic }

taller_reparacio_frontend_formLogin:
    path:     /login
    defaults: { _controller: TallerReparacioFrontendBundle:Login:formLogin}

taller_reparacio_frontend_login:
    path:     /validateLogin
    defaults: { _controller: TallerReparacioFrontendBundle:Login:login}