taller_reparacio_backend_homepage:
    path:     /
    defaults: { _controller: TallerReparacioBackendBundle:Default:index }

taller_reparacio_backend_consultar_clients:
    path:     /clients
    defaults: { _controller: TallerReparacioBackendBundle:Clients:mostrar }

taller_reparacio_backend_eliminar_clients:
    path:     /clients/eliminar/{nif}
    defaults: { _controller: TallerReparacioBackendBundle:Clients:eliminar }

taller_reparacio_backend_formEditar_clients:
    path:     /clients/formEditar/{nif}
    defaults: { _controller: TallerReparacioBackendBundle:Clients:formEditarClient }

taller_reparacio_backend_editar_clients:
    path:     /clients/editar
    defaults: { _controller: TallerReparacioBackendBundle:Clients:editarClient }

taller_reparacio_backend_formAfegir_clients:
    path:     /clients/formAfegir
    defaults: { _controller: TallerReparacioBackendBundle:Clients:formAfegirClient }

taller_reparacio_backend_afegir_clients:
    path:     /clients/afegir
    defaults: { _controller: TallerReparacioBackendBundle:Clients:afegirClient }

taller_reparacio_backend_consultar_vehicles:
    path:     /vehicles
    defaults: { _controller: TallerReparacioBackendBundle:Vehicles:mostrar }

taller_reparacio_backend_eliminar_vehicles:
    path:     /vehicles/eliminar{matricula}
    defaults: { _controller: TallerReparacioBackendBundle:Vehicles:eliminar }

taller_reparacio_backend_formEditar_vehicles:
    path:     /vehicles/formEditar/{matricula}
    defaults: { _controller: TallerReparacioBackendBundle:Vehicles:formEditarVehicle }

taller_reparacio_backend_editar_vehicles:
    path:     /vehicles/editar
    defaults: { _controller: TallerReparacioBackendBundle:Vehicles:editarVehicle }

taller_reparacio_backend_consultar_reparacions:
    path:     /reparacions
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:mostrar }

taller_reparacio_backend_eliminar_reparacions:
    path:     /reparacions/eliminar/{codi}
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:eliminar }

taller_reparacio_backend_formEditar_reparacions:
    path:     /reparacions/editar/{codi}
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:formEditarReparacio }

taller_reparacio_backend_editar_reparacions:
    path:     /reparacions/editar
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:editarReparacio }

taller_reparacio_backend_formCrear_reparacions:
    path:     /reparacions/formCrear
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:formCrearReparacio }

taller_reparacio_backend_crear_reparacions:
    path:     /clients/crear
    defaults: { _controller: TallerReparacioBackendBundle:Reparacions:crearReparacio }