<?php

namespace TallerReparacio\BackendBundle\Repository;

/**
 * realitzadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class realitzadesRepository extends \Doctrine\ORM\EntityRepository
{
}
