<?php

namespace TallerReparacio\BackendBundle\Repository;

/**
 * ReparacionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparacionsRepository extends \Doctrine\ORM\EntityRepository
{
}
