<?php

namespace TallerReparacio\BackendBundle\Repository;

/**
 * UsuarisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarisRepository extends \Doctrine\ORM\EntityRepository
{
}
