<?php

namespace TallerReparacio\BackendBundle\Repository;

/**
 * VehiclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiclesRepository extends \Doctrine\ORM\EntityRepository
{
}
