taller_reparacio_backend:
    resource: "@TallerReparacioBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

taller_reparacio_frontend:
    resource: "@TallerReparacioFrontendBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
